export const CHALLENGES = [
  {
    id: "trivia",
    title: "Trivia",
    sport: "Trivia",
    description: "Daily & weekly trivia challenges",
    difficulty: "Easy",
    status: "Active",
    href: "/trivia",
  },
  {
    id: "golf-weekly",
    title: "Golf Weekly",
    sport: "Golf",
    description: "Pick winners for this week's PGA event.",
    difficulty: "Medium",
    status: "Open",
    href: "/sports/golf/weekly",
  },
  {
    id: "nfl-weekly",
    title: "NFL Weekly",
    sport: "NFL",
    description: "Predict winners for the upcoming NFL slate.",
    difficulty: "Medium",
    status: "Open",
    href: "/sports/nfl/weekly",
  },
  {
    id: "nba-daily",
    title: "NBA Daily",
    sport: "NBA",
    description: "Compete in daily and weekly basketball challenges.",
    difficulty: "Medium",
    status: "Coming Soon",
    href: null,
  },
  {
    id: "mlb-weekly",
    title: "MLB Weekly",
    sport: "MLB",
    description: "Make your picks for the latest baseball matchups.",
    difficulty: "Medium",
    status: "Coming Soon",
    href: null,
  },
  {
    id: "nhl-weekly",
    title: "NHL Weekly",
    sport: "NHL",
    description: "Predict winners for the weekly hockey slate.",
    difficulty: "Medium",
    status: "Coming Soon",
    href: null,
  },
  {
    id: "college-football",
    title: "College Football",
    sport: "College Football",
    description: "Join the playoff challenge and pick your champions.",
    difficulty: "Medium",
    status: "Coming Soon",
    href: null,
  },
  {
    id: "march-madness",
    title: "College Basketball",
    sport: "College Basketball",
    description: "Enter your March Madness Bracket.",
    difficulty: "Medium",
    status: "Open",
    href: "/sports/march-madness",
  },
];
