export const teamLogosAtoF: Record<string, string> = {
  "Abilene Christian": "https://a.espncdn.com/i/teamlogos/ncaa/500/2006.png",
  "Air Force": "https://a.espncdn.com/i/teamlogos/ncaa/500/2005.png",
  "Akron": "https://a.espncdn.com/i/teamlogos/ncaa/500/2008.png",
  "Alabama": "https://a.espncdn.com/i/teamlogos/ncaa/500/333.png",
  "Alabama A&M": "https://a.espncdn.com/i/teamlogos/ncaa/500/399.png",
  "Alabama State": "https://a.espncdn.com/i/teamlogos/ncaa/500/399.png",
  "Albany": "https://a.espncdn.com/i/teamlogos/ncaa/500/399.png",
  "Alcorn State": "https://a.espncdn.com/i/teamlogos/ncaa/500/399.png",
  "American": "https://a.espncdn.com/i/teamlogos/ncaa/500/44.png",
  "Appalachian State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2026.png",
  "Arizona": "https://a.espncdn.com/i/teamlogos/ncaa/500/12.png",
  "Arizona State": "https://a.espncdn.com/i/teamlogos/ncaa/500/9.png",
  "Arkansas": "https://a.espncdn.com/i/teamlogos/ncaa/500/8.png",
  "Arkansas State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2032.png",
  "Arkansas-Pine Bluff": "https://a.espncdn.com/i/teamlogos/ncaa/500/2033.png",
  "Army": "https://a.espncdn.com/i/teamlogos/ncaa/500/349.png",
  "Auburn": "https://a.espncdn.com/i/teamlogos/ncaa/500/2.png",
  "Austin Peay": "https://a.espncdn.com/i/teamlogos/ncaa/500/2046.png",

  "Ball State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2050.png",
  "Baylor": "https://a.espncdn.com/i/teamlogos/ncaa/500/239.png",
  "Bellarmine": "https://a.espncdn.com/i/teamlogos/ncaa/500/93.png",
  "Belmont": "https://a.espncdn.com/i/teamlogos/ncaa/500/2057.png",
  "Bethune-Cookman": "https://a.espncdn.com/i/teamlogos/ncaa/500/2061.png",
  "Binghamton": "https://a.espncdn.com/i/teamlogos/ncaa/500/2066.png",
  "Boise State": "https://a.espncdn.com/i/teamlogos/ncaa/500/68.png",
  "Boston College": "https://a.espncdn.com/i/teamlogos/ncaa/500/103.png",
  "Boston University": "https://a.espncdn.com/i/teamlogos/ncaa/500/104.png",
  "Bowling Green": "https://a.espncdn.com/i/teamlogos/ncaa/500/189.png",
  "Bradley": "https://a.espncdn.com/i/teamlogos/ncaa/500/2086.png",
  "Brown": "https://a.espncdn.com/i/teamlogos/ncaa/500/225.png",
  "Bryant": "https://a.espncdn.com/i/teamlogos/ncaa/500/2089.png",
  "Bucknell": "https://a.espncdn.com/i/teamlogos/ncaa/500/2083.png",
  "Buffalo": "https://a.espncdn.com/i/teamlogos/ncaa/500/2084.png",
  "Butler": "https://a.espncdn.com/i/teamlogos/ncaa/500/2086.png",
  "BYU": "https://a.espncdn.com/i/teamlogos/ncaa/500/252.png",

  "Cal Baptist": "https://a.espncdn.com/i/teamlogos/ncaa/500/1129.png",
  "Cal Poly": "https://a.espncdn.com/i/teamlogos/ncaa/500/13.png",
  "Cal State Bakersfield": "https://a.espncdn.com/i/teamlogos/ncaa/500/293.png",
  "Cal State Fullerton": "https://a.espncdn.com/i/teamlogos/ncaa/500/14.png",
  "Cal State Northridge": "https://a.espncdn.com/i/teamlogos/ncaa/500/15.png",
  "California": "https://a.espncdn.com/i/teamlogos/ncaa/500/25.png",
  "Campbell": "https://a.espncdn.com/i/teamlogos/ncaa/500/2090.png",
  "Canisius": "https://a.espncdn.com/i/teamlogos/ncaa/500/2093.png",
  "Central Arkansas": "https://a.espncdn.com/i/teamlogos/ncaa/500/2097.png",
  "Central Connecticut": "https://a.espncdn.com/i/teamlogos/ncaa/500/2099.png",
  "Central Michigan": "https://a.espncdn.com/i/teamlogos/ncaa/500/2117.png",
  "Charleston": "https://a.espncdn.com/i/teamlogos/ncaa/500/232.png",
  "Charleston Southern": "https://a.espncdn.com/i/teamlogos/ncaa/500/2115.png",
  "Charlotte": "https://a.espncdn.com/i/teamlogos/ncaa/500/2429.png",
  "Chattanooga": "https://a.espncdn.com/i/teamlogos/ncaa/500/2116.png",
  "Chicago State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2118.png",
  "Cincinnati": "https://a.espncdn.com/i/teamlogos/ncaa/500/2132.png",
  "Clemson": "https://a.espncdn.com/i/teamlogos/ncaa/500/228.png",
  "Cleveland State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2133.png",
  "Coastal Carolina": "https://a.espncdn.com/i/teamlogos/ncaa/500/324.png",
  "Colgate": "https://a.espncdn.com/i/teamlogos/ncaa/500/2142.png",
  "Colorado": "https://a.espncdn.com/i/teamlogos/ncaa/500/38.png",
  "Colorado State": "https://a.espncdn.com/i/teamlogos/ncaa/500/36.png",
  "Columbia": "https://a.espncdn.com/i/teamlogos/ncaa/500/171.png",
  "Connecticut": "https://a.espncdn.com/i/teamlogos/ncaa/500/41.png",
  "Coppin State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2150.png",
  "Cornell": "https://a.espncdn.com/i/teamlogos/ncaa/500/172.png",
  "Creighton": "https://a.espncdn.com/i/teamlogos/ncaa/500/156.png",

  "Dartmouth": "https://a.espncdn.com/i/teamlogos/ncaa/500/159.png",
  "Davidson": "https://a.espncdn.com/i/teamlogos/ncaa/500/2166.png",
  "Dayton": "https://a.espncdn.com/i/teamlogos/ncaa/500/2168.png",
  "Delaware": "https://a.espncdn.com/i/teamlogos/ncaa/500/2169.png",
  "Delaware State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2170.png",
  "Denver": "https://a.espncdn.com/i/teamlogos/ncaa/500/2181.png",
  "DePaul": "https://a.espncdn.com/i/teamlogos/ncaa/500/305.png",
  "Detroit Mercy": "https://a.espncdn.com/i/teamlogos/ncaa/500/2172.png",
  "Drake": "https://a.espncdn.com/i/teamlogos/ncaa/500/2183.png",
  "Drexel": "https://a.espncdn.com/i/teamlogos/ncaa/500/2184.png",
  "Duke": "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  "Duquesne": "https://a.espncdn.com/i/teamlogos/ncaa/500/2188.png",

  "East Carolina": "https://a.espncdn.com/i/teamlogos/ncaa/500/151.png",
  "East Tennessee State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2193.png",
  "Eastern Illinois": "https://a.espncdn.com/i/teamlogos/ncaa/500/2197.png",
  "Eastern Kentucky": "https://a.espncdn.com/i/teamlogos/ncaa/500/2198.png",
  "Eastern Michigan": "https://a.espncdn.com/i/teamlogos/ncaa/500/2199.png",
  "Eastern Washington": "https://a.espncdn.com/i/teamlogos/ncaa/500/331.png",
  "Elon": "https://a.espncdn.com/i/teamlogos/ncaa/500/2210.png",
  "Evansville": "https://a.espncdn.com/i/teamlogos/ncaa/500/2217.png",

  "Fairfield": "https://a.espncdn.com/i/teamlogos/ncaa/500/2221.png",
  "Fairleigh Dickinson": "https://a.espncdn.com/i/teamlogos/ncaa/500/2222.png",
  "Florida": "https://a.espncdn.com/i/teamlogos/ncaa/500/57.png",
  "Florida A&M": "https://a.espncdn.com/i/teamlogos/ncaa/500/50.png",
  "Florida Atlantic": "https://a.espncdn.com/i/teamlogos/ncaa/500/2226.png",
  "Florida Gulf Coast": "https://a.espncdn.com/i/teamlogos/ncaa/500/526.png",
  "Florida International": "https://a.espncdn.com/i/teamlogos/ncaa/500/2229.png",
  "Florida State": "https://a.espncdn.com/i/teamlogos/ncaa/500/52.png",
  "Fordham": "https://a.espncdn.com/i/teamlogos/ncaa/500/2230.png",
  "Fresno State": "https://a.espncdn.com/i/teamlogos/ncaa/500/278.png",
  "Furman": "https://a.espncdn.com/i/teamlogos/ncaa/500/231.png"
}
export const teamLogosGtoL: Record<string, string> = {
  "Gardner-Webb": "https://a.espncdn.com/i/teamlogos/ncaa/500/2241.png",
  "George Mason": "https://a.espncdn.com/i/teamlogos/ncaa/500/2244.png",
  "George Washington": "https://a.espncdn.com/i/teamlogos/ncaa/500/45.png",
  "Georgetown": "https://a.espncdn.com/i/teamlogos/ncaa/500/46.png",
  "Georgia": "https://a.espncdn.com/i/teamlogos/ncaa/500/61.png",
  "Georgia Southern": "https://a.espncdn.com/i/teamlogos/ncaa/500/290.png",
  "Georgia State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2247.png",
  "Georgia Tech": "https://a.espncdn.com/i/teamlogos/ncaa/500/59.png",
  "Gonzaga": "https://a.espncdn.com/i/teamlogos/ncaa/500/2250.png",
  "Grambling State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2251.png",
  "Grand Canyon": "https://a.espncdn.com/i/teamlogos/ncaa/500/2253.png",
  "Green Bay": "https://a.espncdn.com/i/teamlogos/ncaa/500/2254.png",

  "Hampton": "https://a.espncdn.com/i/teamlogos/ncaa/500/47.png",
  "Harvard": "https://a.espncdn.com/i/teamlogos/ncaa/500/108.png",
  "Hawaii": "https://a.espncdn.com/i/teamlogos/ncaa/500/62.png",
  "High Point": "https://a.espncdn.com/i/teamlogos/ncaa/500/2277.png",
  "Hofstra": "https://a.espncdn.com/i/teamlogos/ncaa/500/2279.png",
  "Holy Cross": "https://a.espncdn.com/i/teamlogos/ncaa/500/107.png",
  "Houston": "https://a.espncdn.com/i/teamlogos/ncaa/500/248.png",
  "Houston Christian": "https://a.espncdn.com/i/teamlogos/ncaa/500/2276.png",
  "Howard": "https://a.espncdn.com/i/teamlogos/ncaa/500/47.png",

  "Idaho": "https://a.espncdn.com/i/teamlogos/ncaa/500/70.png",
  "Idaho State": "https://a.espncdn.com/i/teamlogos/ncaa/500/71.png",
  "Illinois": "https://a.espncdn.com/i/teamlogos/ncaa/500/356.png",
  "Illinois State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2287.png",
  "Incarnate Word": "https://a.espncdn.com/i/teamlogos/ncaa/500/291.png",
  "Indiana": "https://a.espncdn.com/i/teamlogos/ncaa/500/84.png",
  "Indiana State": "https://a.espncdn.com/i/teamlogos/ncaa/500/85.png",
  "Iona": "https://a.espncdn.com/i/teamlogos/ncaa/500/86.png",
  "Iowa": "https://a.espncdn.com/i/teamlogos/ncaa/500/2294.png",
  "Iowa State": "https://a.espncdn.com/i/teamlogos/ncaa/500/66.png",
  "IPFW": "https://a.espncdn.com/i/teamlogos/ncaa/500/282.png",

  "Jackson State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2296.png",
  "Jacksonville": "https://a.espncdn.com/i/teamlogos/ncaa/500/293.png",
  "Jacksonville State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2297.png",
  "James Madison": "https://a.espncdn.com/i/teamlogos/ncaa/500/256.png",

  "Kansas": "https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png",
  "Kansas State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png",
  "Kennesaw State": "https://a.espncdn.com/i/teamlogos/ncaa/500/338.png",
  "Kent State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2309.png",
  "Kentucky": "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",

  "La Salle": "https://a.espncdn.com/i/teamlogos/ncaa/500/2320.png",
  "Lafayette": "https://a.espncdn.com/i/teamlogos/ncaa/500/2321.png",
  "Lamar": "https://a.espncdn.com/i/teamlogos/ncaa/500/2322.png",
  "Lehigh": "https://a.espncdn.com/i/teamlogos/ncaa/500/2324.png",
  "Liberty": "https://a.espncdn.com/i/teamlogos/ncaa/500/2335.png",
  "Lipscomb": "https://a.espncdn.com/i/teamlogos/ncaa/500/2336.png",
  "Long Beach State": "https://a.espncdn.com/i/teamlogos/ncaa/500/246.png",
  "Long Island": "https://a.espncdn.com/i/teamlogos/ncaa/500/2340.png",
  "Longwood": "https://a.espncdn.com/i/teamlogos/ncaa/500/2341.png",
  "Louisiana": "https://a.espncdn.com/i/teamlogos/ncaa/500/309.png",
  "Louisiana Tech": "https://a.espncdn.com/i/teamlogos/ncaa/500/2348.png",
  "Louisville": "https://a.espncdn.com/i/teamlogos/ncaa/500/97.png"
}
export const teamLogosMtoR: Record<string, string> = {
  "Maine": "https://a.espncdn.com/i/teamlogos/ncaa/500/311.png",
  "Manhattan": "https://a.espncdn.com/i/teamlogos/ncaa/500/2363.png",
  "Marist": "https://a.espncdn.com/i/teamlogos/ncaa/500/2364.png",
  "Marquette": "https://a.espncdn.com/i/teamlogos/ncaa/500/269.png",
  "Marshall": "https://a.espncdn.com/i/teamlogos/ncaa/500/276.png",
  "Maryland": "https://a.espncdn.com/i/teamlogos/ncaa/500/120.png",
  "Maryland Eastern Shore": "https://a.espncdn.com/i/teamlogos/ncaa/500/2371.png",
  "Massachusetts": "https://a.espncdn.com/i/teamlogos/ncaa/500/113.png",
  "McNeese State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2377.png",
  "Memphis": "https://a.espncdn.com/i/teamlogos/ncaa/500/235.png",
  "Mercer": "https://a.espncdn.com/i/teamlogos/ncaa/500/2382.png",
  "Miami (FL)": "https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png",
  "Miami (OH)": "https://a.espncdn.com/i/teamlogos/ncaa/500/193.png",
  "Michigan": "https://a.espncdn.com/i/teamlogos/ncaa/500/130.png",
  "Michigan State": "https://a.espncdn.com/i/teamlogos/ncaa/500/127.png",
  "Middle Tennessee": "https://a.espncdn.com/i/teamlogos/ncaa/500/2393.png",
  "Minnesota": "https://a.espncdn.com/i/teamlogos/ncaa/500/135.png",
  "Mississippi State": "https://a.espncdn.com/i/teamlogos/ncaa/500/344.png",
  "Mississippi Valley State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2400.png",
  "Missouri": "https://a.espncdn.com/i/teamlogos/ncaa/500/142.png",
  "Missouri State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2403.png",
  "Monmouth": "https://a.espncdn.com/i/teamlogos/ncaa/500/2405.png",
  "Montana": "https://a.espncdn.com/i/teamlogos/ncaa/500/147.png",
  "Montana State": "https://a.espncdn.com/i/teamlogos/ncaa/500/149.png",
  "Morehead State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2413.png",
  "Morgan State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2415.png",
  "Mount St. Mary's": "https://a.espncdn.com/i/teamlogos/ncaa/500/2420.png",
  "Murray State": "https://a.espncdn.com/i/teamlogos/ncaa/500/93.png",

  "Navy": "https://a.espncdn.com/i/teamlogos/ncaa/500/2426.png",
  "NC State": "https://a.espncdn.com/i/teamlogos/ncaa/500/152.png",
  "Nebraska": "https://a.espncdn.com/i/teamlogos/ncaa/500/158.png",
  "Nevada": "https://a.espncdn.com/i/teamlogos/ncaa/500/2440.png",
  "New Hampshire": "https://a.espncdn.com/i/teamlogos/ncaa/500/160.png",
  "New Mexico": "https://a.espncdn.com/i/teamlogos/ncaa/500/167.png",
  "New Mexico State": "https://a.espncdn.com/i/teamlogos/ncaa/500/166.png",
  "New Orleans": "https://a.espncdn.com/i/teamlogos/ncaa/500/2445.png",
  "Niagara": "https://a.espncdn.com/i/teamlogos/ncaa/500/2447.png",
  "Nicholls State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2449.png",
  "Norfolk State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2452.png",
  "North Alabama": "https://a.espncdn.com/i/teamlogos/ncaa/500/1129.png",
  "North Carolina": "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png",
  "North Carolina A&T": "https://a.espncdn.com/i/teamlogos/ncaa/500/2458.png",
  "North Carolina Central": "https://a.espncdn.com/i/teamlogos/ncaa/500/2459.png",
  "North Dakota": "https://a.espncdn.com/i/teamlogos/ncaa/500/155.png",
  "North Dakota State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2449.png",
  "North Florida": "https://a.espncdn.com/i/teamlogos/ncaa/500/2463.png",
  "North Texas": "https://a.espncdn.com/i/teamlogos/ncaa/500/249.png",
  "Northeastern": "https://a.espncdn.com/i/teamlogos/ncaa/500/2469.png",
  "Northern Arizona": "https://a.espncdn.com/i/teamlogos/ncaa/500/2464.png",
  "Northern Colorado": "https://a.espncdn.com/i/teamlogos/ncaa/500/2465.png",
  "Northern Illinois": "https://a.espncdn.com/i/teamlogos/ncaa/500/2470.png",
  "Northern Iowa": "https://a.espncdn.com/i/teamlogos/ncaa/500/2468.png",
  "Northern Kentucky": "https://a.espncdn.com/i/teamlogos/ncaa/500/1129.png",
  "Northwestern": "https://a.espncdn.com/i/teamlogos/ncaa/500/77.png",
  "Northwestern State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2472.png",

  "Notre Dame": "https://a.espncdn.com/i/teamlogos/ncaa/500/87.png",

  "Oakland": "https://a.espncdn.com/i/teamlogos/ncaa/500/2473.png",
  "Ohio": "https://a.espncdn.com/i/teamlogos/ncaa/500/195.png",
  "Ohio State": "https://a.espncdn.com/i/teamlogos/ncaa/500/194.png",
  "Oklahoma": "https://a.espncdn.com/i/teamlogos/ncaa/500/201.png",
  "Oklahoma State": "https://a.espncdn.com/i/teamlogos/ncaa/500/197.png",
  "Old Dominion": "https://a.espncdn.com/i/teamlogos/ncaa/500/295.png",
  "Ole Miss": "https://a.espncdn.com/i/teamlogos/ncaa/500/145.png",
  "Omaha": "https://a.espncdn.com/i/teamlogos/ncaa/500/2430.png",
  "Oral Roberts": "https://a.espncdn.com/i/teamlogos/ncaa/500/197.png",
  "Oregon": "https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png",
  "Oregon State": "https://a.espncdn.com/i/teamlogos/ncaa/500/204.png",

  "Pacific": "https://a.espncdn.com/i/teamlogos/ncaa/500/254.png",
  "Penn": "https://a.espncdn.com/i/teamlogos/ncaa/500/219.png",
  "Penn State": "https://a.espncdn.com/i/teamlogos/ncaa/500/213.png",
  "Pepperdine": "https://a.espncdn.com/i/teamlogos/ncaa/500/253.png",
  "Pittsburgh": "https://a.espncdn.com/i/teamlogos/ncaa/500/221.png",
  "Portland": "https://a.espncdn.com/i/teamlogos/ncaa/500/250.png",
  "Portland State": "https://a.espncdn.com/i/teamlogos/ncaa/500/250.png",
  "Prairie View A&M": "https://a.espncdn.com/i/teamlogos/ncaa/500/2504.png",
  "Presbyterian": "https://a.espncdn.com/i/teamlogos/ncaa/500/2505.png",
  "Princeton": "https://a.espncdn.com/i/teamlogos/ncaa/500/163.png",
  "Providence": "https://a.espncdn.com/i/teamlogos/ncaa/500/2507.png",
  "Purdue": "https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png",

  "Quinnipiac": "https://a.espncdn.com/i/teamlogos/ncaa/500/2510.png",

  "Radford": "https://a.espncdn.com/i/teamlogos/ncaa/500/2511.png",
  "Rhode Island": "https://a.espncdn.com/i/teamlogos/ncaa/500/227.png",
  "Rice": "https://a.espncdn.com/i/teamlogos/ncaa/500/242.png",
  "Richmond": "https://a.espncdn.com/i/teamlogos/ncaa/500/257.png",
  "Rider": "https://a.espncdn.com/i/teamlogos/ncaa/500/2514.png",
  "Robert Morris": "https://a.espncdn.com/i/teamlogos/ncaa/500/2516.png",
  "Rutgers": "https://a.espncdn.com/i/teamlogos/ncaa/500/164.png"
}
export const teamLogosStoZ: Record<string, string> = {
  "Sacramento State": "https://a.espncdn.com/i/teamlogos/ncaa/500/16.png",
  "Sacred Heart": "https://a.espncdn.com/i/teamlogos/ncaa/500/2520.png",
  "Saint Francis (PA)": "https://a.espncdn.com/i/teamlogos/ncaa/500/259.png",
  "Saint Joseph's": "https://a.espncdn.com/i/teamlogos/ncaa/500/260.png",
  "Saint Louis": "https://a.espncdn.com/i/teamlogos/ncaa/500/139.png",
  "Saint Mary's": "https://a.espncdn.com/i/teamlogos/ncaa/500/2608.png",
  "Saint Peter's": "https://a.espncdn.com/i/teamlogos/ncaa/500/2610.png",
  "Sam Houston": "https://a.espncdn.com/i/teamlogos/ncaa/500/2535.png",
  "Samford": "https://a.espncdn.com/i/teamlogos/ncaa/500/2536.png",
  "San Diego": "https://a.espncdn.com/i/teamlogos/ncaa/500/301.png",
  "San Diego State": "https://a.espncdn.com/i/teamlogos/ncaa/500/21.png",
  "San Francisco": "https://a.espncdn.com/i/teamlogos/ncaa/500/2539.png",
  "San Jose State": "https://a.espncdn.com/i/teamlogos/ncaa/500/23.png",
  "Santa Clara": "https://a.espncdn.com/i/teamlogos/ncaa/500/2541.png",
  "Seattle": "https://a.espncdn.com/i/teamlogos/ncaa/500/2542.png",
  "Seton Hall": "https://a.espncdn.com/i/teamlogos/ncaa/500/2550.png",
  "Siena": "https://a.espncdn.com/i/teamlogos/ncaa/500/2553.png",
  "SMU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2567.png",
  "South Alabama": "https://a.espncdn.com/i/teamlogos/ncaa/500/6.png",
  "South Carolina": "https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png",
  "South Carolina State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2578.png",
  "South Dakota": "https://a.espncdn.com/i/teamlogos/ncaa/500/2572.png",
  "South Dakota State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2571.png",
  "South Florida": "https://a.espncdn.com/i/teamlogos/ncaa/500/58.png",
  "Southeast Missouri State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2546.png",
  "Southeastern Louisiana": "https://a.espncdn.com/i/teamlogos/ncaa/500/2547.png",
  "Southern": "https://a.espncdn.com/i/teamlogos/ncaa/500/2580.png",
  "Southern Illinois": "https://a.espncdn.com/i/teamlogos/ncaa/500/2578.png",
  "Southern Miss": "https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png",
  "Southern Utah": "https://a.espncdn.com/i/teamlogos/ncaa/500/2581.png",
  "St. Bonaventure": "https://a.espncdn.com/i/teamlogos/ncaa/500/179.png",
  "St. John's": "https://a.espncdn.com/i/teamlogos/ncaa/500/2599.png",
  "Stanford": "https://a.espncdn.com/i/teamlogos/ncaa/500/24.png",
  "Stephen F. Austin": "https://a.espncdn.com/i/teamlogos/ncaa/500/2617.png",
  "Stetson": "https://a.espncdn.com/i/teamlogos/ncaa/500/2619.png",
  "Stonehill": "https://a.espncdn.com/i/teamlogos/ncaa/500/2620.png",
  "Stony Brook": "https://a.espncdn.com/i/teamlogos/ncaa/500/2618.png",

  "Syracuse": "https://a.espncdn.com/i/teamlogos/ncaa/500/183.png",

  "TCU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png",
  "Temple": "https://a.espncdn.com/i/teamlogos/ncaa/500/218.png",
  "Tennessee": "https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png",
  "Tennessee State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2634.png",
  "Tennessee Tech": "https://a.espncdn.com/i/teamlogos/ncaa/500/2635.png",
  "Texas": "https://a.espncdn.com/i/teamlogos/ncaa/500/251.png",
  "Texas A&M": "https://a.espncdn.com/i/teamlogos/ncaa/500/245.png",
  "Texas A&M-Commerce": "https://a.espncdn.com/i/teamlogos/ncaa/500/245.png",
  "Texas A&M-Corpus Christi": "https://a.espncdn.com/i/teamlogos/ncaa/500/246.png",
  "Texas Southern": "https://a.espncdn.com/i/teamlogos/ncaa/500/2640.png",
  "Texas State": "https://a.espncdn.com/i/teamlogos/ncaa/500/326.png",
  "Texas Tech": "https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png",
  "The Citadel": "https://a.espncdn.com/i/teamlogos/ncaa/500/267.png",
  "Toledo": "https://a.espncdn.com/i/teamlogos/ncaa/500/2649.png",
  "Towson": "https://a.espncdn.com/i/teamlogos/ncaa/500/2651.png",
  "Troy": "https://a.espncdn.com/i/teamlogos/ncaa/500/2653.png",
  "Tulane": "https://a.espncdn.com/i/teamlogos/ncaa/500/2655.png",
  "Tulsa": "https://a.espncdn.com/i/teamlogos/ncaa/500/202.png",

  "UAB": "https://a.espncdn.com/i/teamlogos/ncaa/500/5.png",
  "UC Davis": "https://a.espncdn.com/i/teamlogos/ncaa/500/302.png",
  "UC Irvine": "https://a.espncdn.com/i/teamlogos/ncaa/500/300.png",
  "UC Riverside": "https://a.espncdn.com/i/teamlogos/ncaa/500/301.png",
  "UC San Diego": "https://a.espncdn.com/i/teamlogos/ncaa/500/302.png",
  "UC Santa Barbara": "https://a.espncdn.com/i/teamlogos/ncaa/500/302.png",
  "UCF": "https://a.espncdn.com/i/teamlogos/ncaa/500/2116.png",
  "UCLA": "https://a.espncdn.com/i/teamlogos/ncaa/500/26.png",
  "UConn": "https://a.espncdn.com/i/teamlogos/ncaa/500/41.png",
  "UIC": "https://a.espncdn.com/i/teamlogos/ncaa/500/263.png",
  "UL Monroe": "https://a.espncdn.com/i/teamlogos/ncaa/500/2433.png",
  "UMass Lowell": "https://a.espncdn.com/i/teamlogos/ncaa/500/113.png",
  "UNC Asheville": "https://a.espncdn.com/i/teamlogos/ncaa/500/2427.png",
  "UNC Greensboro": "https://a.espncdn.com/i/teamlogos/ncaa/500/2428.png",
  "UNC Wilmington": "https://a.espncdn.com/i/teamlogos/ncaa/500/2430.png",
  "UNLV": "https://a.espncdn.com/i/teamlogos/ncaa/500/2439.png",
  "USC": "https://a.espncdn.com/i/teamlogos/ncaa/500/30.png",
  "UT Arlington": "https://a.espncdn.com/i/teamlogos/ncaa/500/246.png",
  "UT Martin": "https://a.espncdn.com/i/teamlogos/ncaa/500/246.png",
  "UT Rio Grande Valley": "https://a.espncdn.com/i/teamlogos/ncaa/500/246.png",
  "UTSA": "https://a.espncdn.com/i/teamlogos/ncaa/500/263.png",
  "Utah": "https://a.espncdn.com/i/teamlogos/ncaa/500/254.png",
  "Utah State": "https://a.espncdn.com/i/teamlogos/ncaa/500/328.png",
  "Utah Valley": "https://a.espncdn.com/i/teamlogos/ncaa/500/328.png",

  "Valparaiso": "https://a.espncdn.com/i/teamlogos/ncaa/500/2674.png",
  "Vanderbilt": "https://a.espncdn.com/i/teamlogos/ncaa/500/238.png",
  "VCU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2670.png",
  "Vermont": "https://a.espncdn.com/i/teamlogos/ncaa/500/261.png",
  "Villanova": "https://a.espncdn.com/i/teamlogos/ncaa/500/222.png",
  "Virginia": "https://a.espncdn.com/i/teamlogos/ncaa/500/258.png",
  "Virginia Tech": "https://a.espncdn.com/i/teamlogos/ncaa/500/259.png",
  "VMI": "https://a.espncdn.com/i/teamlogos/ncaa/500/2678.png",

  "Wagner": "https://a.espncdn.com/i/teamlogos/ncaa/500/2681.png",
  "Wake Forest": "https://a.espncdn.com/i/teamlogos/ncaa/500/154.png",
  "Washington": "https://a.espncdn.com/i/teamlogos/ncaa/500/264.png",
  "Washington State": "https://a.espncdn.com/i/teamlogos/ncaa/500/265.png",
  "Weber State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2687.png",
  "West Virginia": "https://a.espncdn.com/i/teamlogos/ncaa/500/277.png",
  "Western Carolina": "https://a.espncdn.com/i/teamlogos/ncaa/500/2692.png",
  "Western Illinois": "https://a.espncdn.com/i/teamlogos/ncaa/500/2693.png",
  "Western Kentucky": "https://a.espncdn.com/i/teamlogos/ncaa/500/98.png",
  "Western Michigan": "https://a.espncdn.com/i/teamlogos/ncaa/500/2711.png",
  "Wichita State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2724.png",
  "William & Mary": "https://a.espncdn.com/i/teamlogos/ncaa/500/2729.png",
  "Winthrop": "https://a.espncdn.com/i/teamlogos/ncaa/500/2730.png",
  "Wisconsin": "https://a.espncdn.com/i/teamlogos/ncaa/500/275.png",
  "Wofford": "https://a.espncdn.com/i/teamlogos/ncaa/500/2737.png",
  "Wright State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2752.png",
  "Wyoming": "https://a.espncdn.com/i/teamlogos/ncaa/500/2751.png",

  "Xavier": "https://a.espncdn.com/i/teamlogos/ncaa/500/2752.png",

  "Yale": "https://a.espncdn.com/i/teamlogos/ncaa/500/43.png",
  "Youngstown State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2769.png"
}
export const teamLogos = {
  ...teamLogosAtoF,
  ...teamLogosGtoL,
  ...teamLogosMtoR,
  ...teamLogosStoZ
}
